# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check for bug label
      run: |
        if (grep -q "bug" $GITHUB_EVENT_PATH); then
          echo "Bug label found"
          exit 0
        else
          echo "No bug label found"
          exit 1
        fi
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
    - name: Add "needs-triage" label
      if: ${{ !contains(github.event.issue.labels.*.name, 'needs-triage') }}
      uses: peter-evans/create-issue-label@v2
      with:
        color: FFFFFF
        description: Needs triage
        name: needs-triage
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Remove "bug" label
      if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
      uses: peter-evans/create-issue-label@v2
      with:
        color: 000000
        name: bug
        token: ${{ secrets.GITHUB_TOKEN }}
        delete: true
